site_name: smallzh.blog
site_url: https://blog.smallzh.top/

nav:
  - 简介: index.md
  - HelloWorld: concept/hello_world.md
  - 基础概念:
      - 时间: concept/geo_timezone.md
      - 进制: concept/radix.md
      - 编码: concept/encoding.md
      - 正则表达式: concept/regex.md
      - 随机数: concept/random.md
      - 贝塞尔曲线: concept/bezier.md
  - 计算机:
      - 硬件: concept/hardware.md
      - 操作系统: concept/os.md
      - 终端与Shell: concept/terminal.md
      - 机械键盘和Vim : qu_img/rk61_keyboard.md
      - 网络: concept/network.md
      - Html5&CSS3: concept/h5_css3.md
      - 后端服务: concept/software_server.md
      - Docker使用: other/docker_start_order.md
      - Podman使用: other/use_podman.md
  - 精句:
      - 英文: significance/english.md
      - 中文: significance/chinese.md
  - 趣图:
      - 你看到了什么? : qu_img/tizi.md
      - 搜狗双拼输入法 : qu_img/sou_gou_shuang_pin.md
      - 大脑功能Map : qu_img/brain_map.md
  - 其他:
      - Tool: tool_repo.md
      - Githup: github_repo.md

theme:
  name: smzhbook

extra_css:
  - assets/css/developer-light.css

extra_javascript:
  - assets/js/mermaid-zoom.js

extra:
  site_description: smallzh 的个人博客 - 计算机知识笔记
  site_author: smallzh

plugins: [ ]
